version: '3.9'

services:
  postgres_db:
    container_name: postgres_fastapi
    restart: always
    image: postgres
    environment:
      POSTGRES_USER: "Dev"
      POSTGRES_PASSWORD: "hello"
      POSTGRES_DB: "development_db"
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres: