version: '3.9'

services:
  fastapi:
    container_name: fastapi
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://Dev:hello@db:5432/development_db
    command: sh -c './wait-for db:5432 && alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000'
    depends_on:
      - db
  db:
    container_name: postgres
    restart: always
    image: postgres
    environment:
      POSTGRES_USER: "Dev"
      POSTGRES_PASSWORD: "hello"
      POSTGRES_DB: "development_db"
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres:
